[gha] add basic Linux integration tests

diff --git a/.github/workflows/linux.yml b/.github/workflows/linux.yml
--- a/.github/workflows/linux.yml
+++ b/.github/workflows/linux.yml
@@ -196,17 +196,81 @@ jobs:
       run: |
         snapcraft upload *.snap --release ${{ needs.BuildAndTest.outputs.channel }}
 
+  # Run Linux integration tests for `staging` and `trying` branches
+  Linux-CI:
+    if: ${{ github.event_name == 'push' && contains('refs/heads/staging refs/heads/trying', github.ref) }}
+
+    needs:
+    - BuildAndTest
+
+    runs-on: testflinger
+
+    timeout-minutes: 30
+
+    steps:
+    - name: Write the testflinger job
+      uses: DamianReeves/write-file-action@v1.0
+      with:
+        path: testflinger.yaml
+        contents: |
+          job_queue: vmware-fusion
+          provision_data:
+            vmx: /Users/michal/Virtual Machines.localized/linux.vmwarevm/linux.vmx
+            snapshot: Testflinger
+            image_url: http://cloud-images.ubuntu.com/releases/groovy/release/ubuntu-20.10-server-cloudimg-amd64.img
+            vmx_config:
+              memsize: 2048
+              vhv.enable: true
+              vpmc.enable: true
+
+          test_data:
+            test_cmds: |
+              set -xeuo pipefail
+
+              function _run() \{\{
+                ssh $\{\{SSH_OPTS\}\} "$\{\{DEVICE_USER\}\}@$\{\{DEVICE_IP\}\}" -- "$\{\{@\}\}"
+              \}\}
+
+              # Retry $1 times, with $2 seconds in between tries
+              function _retry() \{\{
+                  tries=$1
+                  interval=$2
+                  shift 2
+                  for try in $( seq $tries ); do
+                      RC=0
+                      "$\{\{@\}\}" || RC=$?
+                      [ $RC -eq 0 -o $try -eq $tries ] && return $RC
+                      sleep $interval;
+                  done
+              \}\}
+
+              function _exit() \{\{
+                _run sudo journalctl -u snap.multipass*
+                return $1
+              \}\}
+
+              _retry 5 30 _run sudo snap install multipass --channel ${{ needs.BuildAndTest.outputs.channel }}
+
+              _retry 2 30 _run /snap/bin/multipass find || _exit $?
+
+              _retry 5 10 _run /snap/bin/multipass start || _exit $?
+              _run /snap/bin/multipass list || _exit $?
+
+    - name: Submit and poll the job
+      run: |
+        testflinger-cli submit --poll testflinger.yaml
+
   # Report result to Bors on `staging` and `trying` branches.
   Linux:
     if: ${{ always() && github.event_name == 'push' && contains('refs/heads/staging refs/heads/trying', github.ref) }}
     needs:
-    - BuildAndTest
+    - Linux-CI
 
     runs-on: ubuntu-latest
 
     steps:
     - name: Report failure
-      if: ${{ needs.BuildAndTest.result != 'success' }}
+      if: ${{ needs.Linux-CI.result != 'success' }}
       run: exit 1
 
   # Dispatch to the private side
